import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export async function getServerSideProps(context) {
  const res = await fetch("https://rickandmortyapi.com/api/character");
  const data = await res.json();

  return {
    props: { data }, // will be passed to the page component as props
  };
}

export default function Home({ data }) {
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-6xl mx-auto">
        <h1 className={styles.title}>Rick and Morty API</h1>
        <div className="grid grid-cols-3 gap-4 mt-5">
          {data.results.map((item, index) => {
            const { id, name, image } = item;
            return (
              <div key={id} className="flex flex-col border border-gray-600 p-5 rounded-lg bg-slate-100 ">
                <h1 className="text-3xl font-bold">{name}</h1>
                <div className="relative w-36 h-36">
                  <Image src={image} alt={name} layout="fill" />
                </div>
              </div>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
